### ISSUE TITLE
Create Issue and PR Templates

### ISSUE THREAD

**Issue by 2k-joker** [2k-joker/weaver-stock-tracker-app#4]
**Description:**
Create PR template to help standardize review workflow, and issue template to standardize how issues should be created. See  [github docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) for instructions on how to do this

**Pain Points:**
- It's annoying to keep typing the different sections manually
- Without templates, it is ~gauranteed~ very likely that issue and pr creation will be inconsistent

**Comment by shoebsd31** [comment]
Hi @2k-joker, 

just created a pull request template. Can you please have a look at it?

**Comment by 2k-joker** [comment]
Done in this [pr](https://github.com/2k-joker/weaver-stock-tracker-app/pull/5). Thanks @shoebsd31
